# Generated by Django 3.2.18 on 2023-04-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('price', models.IntegerField(max_length=64, verbose_name='Цена')),
                ('image', models.CharField(max_length=64, verbose_name='Изображение')),
                ('release_date', models.DateField(max_length=64, verbose_name='Дата выпуска')),
                ('lte_exists', models.CharField(max_length=64, verbose_name='Связь')),
                ('slug', models.SlugField(max_length=64, verbose_name='URL')),
            ],
        ),
    ]
